function [spectra] = spcinitialize(inputSpc)
%SPCinitialize Creates all the fields if not have been done so

%% Set possible fields
datafield = {
            'oriSpc';...
            'oriWaveNum';...
            'bgcor';...
            'spc';...
            'wavenum'...
            };
labelfield = {
            'propertyName';...
            'propertyValue';...
            'oriFileName';...
            'fileName';...
            'spcID';...
            'cellType';...
            'cellProbes';...
            'bgID';...
            'history';...
            };
statsfield = {
            'spcMean';...
            'spcStd';...
            'oriSpcResolution';...
            'spcResolution';...
            'cellNum';...
            };          


%% Check if a field is already created, if not, setfield
for i = 1:length(datafield)    
    if ~spcisfield(inputSpc,datafield{i})
        inputSpc.data.(datafield{i}) = [];
    end
end

for i = 1:length(labelfield)
    if ~spcisfield(inputSpc,labelfield{i})
        inputSpc.label.(labelfield{i}) = [];
    end
end

for i = 1:length(statsfield)
    if ~spcisfield(inputSpc,statsfield{i})
        inputSpc.stats.(statsfield{i}) = [];
    end
end

spectra = inputSpc;

end

